bezkoder:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: SecretKey
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  file:
    name: log.txt
    path: /
  level:
    com:
      capgemini:
        customersecurity: debug
server:
  port: 8085
spring:
  application:
    name: customer-security
  data:
    mongodb:
      uri: mongodb+srv://Annesha:Debnath2000@cluster0.ykmtqbt.mongodb.net/customer?retryWrites=true&w=majority
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi:
      enabled: always
