eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  file:
    name: log.txt
    path: /
  level:
    com:
      capgemini:
        dealservice: debug
server:
  port: 8082
spring:
  application:
    name: deal-service
  data:
    mongodb:
      uri: mongodb+srv://Annesha:Debnath2000@cluster0.ykmtqbt.mongodb.net/deal?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi:
      enabled: always
